In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [2]:
data = pd.read_csv('Admission_Predict.csv')

In [3]:
data

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [4]:
data.drop(columns=['Serial No.'], inplace = True)

In [5]:
data.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,337,118,4,4.5,4.5,9.65,1,0.92
1,324,107,4,4.0,4.5,8.87,1,0.76
2,316,104,3,3.0,3.5,8.00,1,0.72
3,322,110,3,3.5,2.5,8.67,1,0.80
4,314,103,2,2.0,3.0,8.21,0,0.65

In [6]:
X = data.iloc[:,0:-1]
y = data.iloc[:,-1]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1)

In [8]:
X_train

     GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
93         301           97                  2  3.0   3.0  7.88         1
23         334          119                  5  5.0   4.5  9.70         1
299        305          112                  3  3.0   3.5  8.65         0
13         307          109                  3  4.0   3.0  8.00         1
90         318          106                  2  4.0   4.0  7.92         1
..         ...          ...                ...  ...   ...   ...       ...
255        307          110                  4  4.0   4.5  8.37         0
72         321          111                  5  5.0   5.0  9.45         1
396        325          107                  3  3.0   3.5  9.11         1
235        326          111                  5  4.5   4.0  9.23         1
37         300          105                  1  1.0   2.0  7.80         0

[320 rows x 7 columns]

In [9]:

scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
model = Sequential()

model.add(Dense(7, activation='relu', input_dim=7))
model.add(Dense(7, activation='relu'))
model.add(Dense(1, activation ='linear'))

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 7)                 56

 dense_1 (Dense)             (None, 7)                 56

 dense_2 (Dense)             (None, 1)                 8

=================================================================
Total params: 120
Trainable params: 120
Non-trainable params: 0
_________________________________________________________________

In [12]:
model.compile(loss='mean_squared_error', optimizer='Adam')

In [13]:
history = model.fit(X_train_scaled, y_train, epochs=100, validation_split=0.2)

Epoch 1/100
8/8 [==============================] - 0s 16ms/step - loss: 0.5244 - val_loss: 0.5276
Epoch 2/100
8/8 [==============================] - 0s 4ms/step - loss: 0.4484 - val_loss: 0.4503
Epoch 3/100
8/8 [==============================] - 0s 4ms/step - loss: 0.3820 - val_loss: 0.3812
Epoch 4/100
8/8 [==============================] - 0s 4ms/step - loss: 0.3213 - val_loss: 0.3195
Epoch 5/100
8/8 [==============================] - 0s 4ms/step - loss: 0.2661 - val_loss: 0.2634
Epoch 6/100
8/8 [==============================] - 0s 4ms/step - loss: 0.2155 - val_loss: 0.2109
Epoch 7/100
8/8 [==============================] - 0s 4ms/step - loss: 0.1689 - val_loss: 0.1619
Epoch 8/100
8/8 [==============================] - 0s 4ms/step - loss: 0.1265 - val_loss: 0.1170
Epoch 9/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0881 - val_loss: 0.0769
Epoch 10/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0556 - val_loss: 0.0442
Epoch 11/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0318 - val_loss: 0.0221
Epoch 12/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0179 - val_loss: 0.0116
Epoch 13/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0127 - val_loss: 0.0086
Epoch 14/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0119 - val_loss: 0.0082
Epoch 15/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0119 - val_loss: 0.0081
Epoch 16/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0117 - val_loss: 0.0080
Epoch 17/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0114 - val_loss: 0.0078
Epoch 18/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0111 - val_loss: 0.0077
Epoch 19/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0109 - val_loss: 0.0077
Epoch 20/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0107 - val_loss: 0.0076
Epoch 21/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0105 - val_loss: 0.0074
Epoch 22/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0102 - val_loss: 0.0072
Epoch 23/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0099 - val_loss: 0.0069
Epoch 24/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0096 - val_loss: 0.0067
Epoch 25/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0093 - val_loss: 0.0065
Epoch 26/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0091 - val_loss: 0.0064
Epoch 27/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0088 - val_loss: 0.0063
Epoch 28/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0086 - val_loss: 0.0064
Epoch 29/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0084 - val_loss: 0.0063
Epoch 30/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0081 - val_loss: 0.0060
Epoch 31/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0080 - val_loss: 0.0059
Epoch 32/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0078 - val_loss: 0.0056
Epoch 33/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0075 - val_loss: 0.0052
Epoch 34/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0072 - val_loss: 0.0049
Epoch 35/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0070 - val_loss: 0.0047
Epoch 36/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0067 - val_loss: 0.0045
Epoch 37/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0066 - val_loss: 0.0044
Epoch 38/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0064 - val_loss: 0.0042
Epoch 39/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0063 - val_loss: 0.0044
Epoch 40/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0061 - val_loss: 0.0042
Epoch 41/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0059 - val_loss: 0.0040
Epoch 42/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0057 - val_loss: 0.0038
Epoch 43/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0055 - val_loss: 0.0037
Epoch 44/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0052 - val_loss: 0.0035
Epoch 45/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0050 - val_loss: 0.0035
Epoch 46/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0049 - val_loss: 0.0035
Epoch 47/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0048 - val_loss: 0.0035
Epoch 48/100
8/8 [==============================] - 0s 6ms/step - loss: 0.0047 - val_loss: 0.0035
Epoch 49/100
8/8 [==============================] - 0s 6ms/step - loss: 0.0047 - val_loss: 0.0036
Epoch 50/100
8/8 [==============================] - 0s 7ms/step - loss: 0.0046 - val_loss: 0.0035
Epoch 51/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0046 - val_loss: 0.0036
Epoch 52/100
8/8 [==============================] - 0s 6ms/step - loss: 0.0045 - val_loss: 0.0036
Epoch 53/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0045 - val_loss: 0.0035
Epoch 54/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0045 - val_loss: 0.0036
Epoch 55/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0044 - val_loss: 0.0036
Epoch 56/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0044 - val_loss: 0.0036
Epoch 57/100
8/8 [==============================] - 0s 6ms/step - loss: 0.0044 - val_loss: 0.0036
Epoch 58/100
8/8 [==============================] - 0s 7ms/step - loss: 0.0044 - val_loss: 0.0036
Epoch 59/100
8/8 [==============================] - 0s 6ms/step - loss: 0.0043 - val_loss: 0.0036
Epoch 60/100
8/8 [==============================] - 0s 7ms/step - loss: 0.0043 - val_loss: 0.0038
Epoch 61/100
8/8 [==============================] - 0s 7ms/step - loss: 0.0043 - val_loss: 0.0036
Epoch 62/100
8/8 [==============================] - 0s 6ms/step - loss: 0.0043 - val_loss: 0.0037
Epoch 63/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0043 - val_loss: 0.0037
Epoch 64/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0042 - val_loss: 0.0036
Epoch 65/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0042 - val_loss: 0.0037
Epoch 66/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0042 - val_loss: 0.0037
Epoch 67/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0042 - val_loss: 0.0037
Epoch 68/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0042 - val_loss: 0.0037
Epoch 69/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0042 - val_loss: 0.0037
Epoch 70/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0042 - val_loss: 0.0037
Epoch 71/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0042 - val_loss: 0.0038
Epoch 72/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0042 - val_loss: 0.0037
Epoch 73/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0041 - val_loss: 0.0037
Epoch 74/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0041 - val_loss: 0.0038
Epoch 75/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0041 - val_loss: 0.0037
Epoch 76/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0041 - val_loss: 0.0037
Epoch 77/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0041 - val_loss: 0.0037
Epoch 78/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0041 - val_loss: 0.0038
Epoch 79/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0041 - val_loss: 0.0037
Epoch 80/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0041 - val_loss: 0.0037
Epoch 81/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0041 - val_loss: 0.0037
Epoch 82/100
8/8 [==============================] - 0s 6ms/step - loss: 0.0041 - val_loss: 0.0037
Epoch 83/100
8/8 [==============================] - 0s 7ms/step - loss: 0.0041 - val_loss: 0.0037
Epoch 84/100

8/8 [==============================] - 0s 5ms/step - loss: 0.0041 - val_loss: 0.0037
Epoch 85/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0041 - val_loss: 0.0037
Epoch 86/100
8/8 [==============================] - 0s 6ms/step - loss: 0.0041 - val_loss: 0.0037
Epoch 87/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0041 - val_loss: 0.0037
Epoch 88/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0041 - val_loss: 0.0036
Epoch 89/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0041 - val_loss: 0.0038
Epoch 90/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0041 - val_loss: 0.0038
Epoch 91/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0040 - val_loss: 0.0037
Epoch 92/100
8/8 [==============================] - 0s 7ms/step - loss: 0.0041 - val_loss: 0.0036
Epoch 93/100
8/8 [==============================] - 0s 7ms/step - loss: 0.0041 - val_loss: 0.0038
Epoch 94/100
8/8 [==============================] - 0s 6ms/step - loss: 0.0041 - val_loss: 0.0036
Epoch 95/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0040 - val_loss: 0.0037
Epoch 96/100
8/8 [==============================] - 0s 6ms/step - loss: 0.0040 - val_loss: 0.0037
Epoch 97/100
8/8 [==============================] - 0s 6ms/step - loss: 0.0040 - val_loss: 0.0037
Epoch 98/100
8/8 [==============================] - 0s 6ms/step - loss: 0.0040 - val_loss: 0.0037
Epoch 99/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0041 - val_loss: 0.0037
Epoch 100/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0040 - val_loss: 0.0036

In [14]:
y_pred = model.predict(X_test_scaled)

3/3 [==============================] - 0s 2ms/step

In [15]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8006939676003796

In [16]:
# Evaluate model on training data
train_loss = model.evaluate(X_train_scaled, y_train, verbose=0)

# Evaluate model on testing data
test_loss = model.evaluate(X_test_scaled, y_test, verbose=0)

print(f"Train Loss: {train_loss:.4f}")
print(f"Test Loss: {test_loss:.4f}")

Train Loss: 0.0039
Test Loss: 0.0046

In [17]:
import numpy as np

train_rmse = np.sqrt(train_loss)
test_rmse = np.sqrt(test_loss)

print(f"Train RMSE: {train_rmse:.4f}")
print(f"Test RMSE: {test_rmse:.4f}")

Train RMSE: 0.0628
Test RMSE: 0.0679

# Save the Model with Pickle

In [19]:
import pickle

with open('Admission_prediction_model.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)

INFO:tensorflow:Assets written to: ram://40745029-c004-49a6-9c07-333be09f9229/assets